account_id = "8259f9bfa45a74a587d6a90822de442d"
workers_dev = true
compatibility_date = "2025-01-08"
main = "./.output/server/index.mjs"
name = 'tv-shows'
compatibility_flags = ['nodejs_compat']
assets = { directory = "./.output/public/", binding = "ASSETS" }

[placement]
  mode = "smart"

[[d1_databases]]
  binding = "DB"
  database_name = "tv_shows"
  database_id = "b7ecb718-2a90-4cab-a329-8ffaf1478085"
  migrations_table = "migrations"
  migrations_dir = "drizzle"

[triggers]
  crons = [
    "*/10 * * * *",
    "0 12 * * *"
  ]

[[routes]]
  pattern = "tv.joebailey.xyz/*"
  zone_id = "8ef065a9318fac4a900a53c7338208f8"

[vars]
  NUXT_MAILGUN_ENDPOINT = "https://api.eu.mailgun.net/v3/joebailey.xyz"
  DB_LOGGING=false

[observability.logs]
  enabled = true
