account_id = "8259f9bfa45a74a587d6a90822de442d"
workers_dev = true
compatibility_date = "2025-01-08"
main = "./.output/server/index.mjs"
name = 'tv-shows'
compatibility_flags = ['nodejs_compat']
assets = { directory = "./.output/public/", binding = "ASSETS" }

[placement]
  mode = "smart"

[[d1_databases]]
  binding = "DB"
  database_name = "tv_shows"
  database_id = "b7ecb718-2a90-4cab-a329-8ffaf1478085"
  migrations_table = "migrations"
  migrations_dir = "drizzle"

[triggers]
  crons = [ "0 12 * * *" ]

[vars]
  CALENDAR_URL = "https://tv.joebailey.xyz/api/calendar/billybidley26@gmail.com"
  NUXT_MAILGUN_ENDPOINT = "https://api.eu.mailgun.net/v3/joebailey.xyz"
  NUXT_PUBLIC_AUTH_JS_BASE_URL = "https://tv.joebailey.xyz"

[observability.logs]
  enabled = true
