account_id = "8259f9bfa45a74a587d6a90822de442d"
workers_dev = true
compatibility_date = "2023-11-15"

[[d1_databases]]
  binding = "DB"
  database_name = "tv_shows"
  database_id = "b7ecb718-2a90-4cab-a329-8ffaf1478085"
  migration_table = "migrations"
  migrations_dir = "drizzle"
